version: '3'

services:

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=testDB
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306

  api:
    build: .
    restart: on-failure
    depends_on:
      - mysql
    ports:
      - 8080:8080
    links:
      - mysql:mysql