spring:
  datasource:
    url: jdbc:mysql://mysql:3306/testDB?useSSL=false&allowPublicKeyRetrieval=true
    username: user
    password: password
    initialization-mode: always
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true

file:
  storage:
    path: ./img